dockerRun:
	docker run -d -p 9090:3000 --name wiki --restart unless-stopped \
            -v /Users/paul/src/wiki/config.yml:/wiki/config.yml \
            -v /Users/paul/src/wiki/database.sqlite:/wiki/database.sqlite \
            requarks/wiki:2


            -v /Users/paul/src/wiki:/wiki \
